
service: localstack-lambda

plugins:
  - serverless-localstack
  - serverless-offline
  - serverless-functions-base-path

custom:
  functionsBasePath: build/src-ts
  localstack:
    debug: true
    stages:
     - local
     - dev
  endpoints:
    GET - http://localhost:4567/restapis/txwn2s2eog/local/_user_request_/v1/request

    

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x


functions:
  lambdaHandler:
    handler: app.lambdaHandler
    events:
      - http:
         path: lambdaHandler
         method: get
         